CREATE TABLE CUSTOMER(ID BIGINT PRIMARY KEY,
                      NAME VARCHAR(255) NOT NULL,
                      PHONE_NUMBER VARCHAR(32) NOT NULL);
CREATE TABLE PURCHASE_ORDER(ID BIGINT PRIMARY KEY,
                   CUSTOMER_ID BIGINT REFERENCES CUSTOMER(ID) NOT NULL,
                   TRANSACTION_AMOUNT NUMERIC(15, 2) NOT NULL,
                   TRANSACTION_DATE TIMESTAMP NOT NULL);
